version: "3"

services:
  database:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    volumes:
      - db_storage:/var/lib/mysql:rw
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ant
      MYSQL_PASSWORD: ant
      MYSQL_USER: ant
      MYSQL_DATABASE: ant

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: ant
      PMA_PASSWORD: ant
    depends_on:
      - database

volumes:
  db_storage: